# -*- coding: utf-8 -*-
"""Copia de TAREA 1 OFICIAL ALGORITMOS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q8XbdNbAKeWLjpq-xJB_tavUOSUht1Ds

# CC3001 Otoño 2023 Tarea 1 [Gabriela Urbina González]

# Pilas de arena abelianas

### Profesores
Sección 1 Iván Sipirán •
Sección 2 Patricio Poblete •
Sección 3 Nelson Baloian

# Introducción
El objetivo de esta tarea es estudiar un problema inspirado en un fenómeno físico, a través de un modelo matemático, el cual si bien es sencillo, produce resultados que presentan una estructura muy interesante.

<img src="https://ivan-sipiran.com/downloads/arena.png" alt= “” width="200">

La idea es que si uno va formando una pila de arena, llega un momento en que se produce un derrumbe, y la arena de esa pila se derrama hacia los lugares vecinos, estos a su vez se pueden derrumbar, y el proceso continúa hasta que finalmente se estabiliza.

Para estudiar este proceso, usaremos un modelo ultra simplificado. Supondremos que la arena se deposita sobre una superficie plana, la cual está dividida en pequeñas celdas cuadradas, las cuales forman un tablero como se muestra en la siguiente figura:

<img src="https://ivan-sipiran.com/downloads/tablero.png" alt= “” width="100">

El modelo supone que si se apilan demasiados granos de arena en una celda, se produce un derrumbe. En particular, la regla es que si en una celda hay 4 o más granos, se le quitan 4 granos, que se reparten equitativamente hacia las celdas vecinas en los cuatro puntos cardinales.

Para simular este proceso, supondremos que cada celda almacena un número entero, que es la cantidad de granos almacenados en su interior. Aplicando la regla antes descrita (y suponiendo que las celdas que aparecen vacías tienen cero granos), desde la configuración

<img src="https://ivan-sipiran.com/downloads/tablero1.png" alt= “” width="100">

se pasaría a

<img src="https://ivan-sipiran.com/downloads/tablero2.png" alt= “” width="100">

Cuando hay más de una casilla con exceso de granos de arena, la regla se puede aplicar a ellas en cualquier orden y el resultado final es el mismo. Esta propiedad es la que hace que estas pilas de arena se llamen abelianas.

La idea es partir desde una configuración inicial, y luego aplicar esta regla en todos los casilleros que se pueda, hasta que no quede ninguno que tenga 4 o más granos de arena. Esa configuración final la vamos a visualizar asignando un color distinto a cada número de granos.

En particular, nos va a interesar estudiar lo que ocurre cuando la configuración inicial tiene todas las celdas vacías, excepto la del centro, en la cual hay $N$ granos de arena (donde $N$ es un parámetro del problema).

Note que en teoría el tablero es infinito en el sentido que siempre hay espacio para colocar los granos de arena que se van distribuyendo. Para su simulación, usted debe calcular un tamaño del tablero lo suficientemente grande como para estar seguro que ningún grano de arena se salga hacia afuera de los bordes (calcule la máxima área que se puede cubrir con $N$ granos de arena, y después calcule cuan grande debe ser el tablero  para poder contener esa área).

# Tarea

## Parte 1
Usted debe escribir una función en Python llamada ``arena``, tal que dado un valor de $N$, simule el proceso anteriormente descrito hasta que se estabilice. El programa debe contar e imprimir el número total de veces que se aplicó la regla que distribuye granos de arena hacia los vecinos. Además, debe visualizar en la pantalla el tablero resultante, usando los métodos que se describen más adelante.

Por ejemplo, al simular con $N=10000$, la figura que resulta es

<img src="https://ivan-sipiran.com/downloads/tablero3.png" alt= “” width="250">

La idea va a ser ejecutar la función con un valor de $N$ dado por el profesor ($N=128$) y luego con valores crecientes de $N$, hasta el mayor número que pueda alcanzar dentro de un tiempo de ejecución razonable.

Escriba a continuación la definición de su función:
"""

import matplotlib.pyplot as plt
import numpy as np
import math
def arena(N):
  if N < 4:
    mat = np.zeros((3,3))
    mat[1][1] = N
    counter = 0
    print(counter)
    return mat
  counter = 0
  r = int(math.sqrt(N/math.pi))
  size = int(r*2) #aumentar el tamaño del tablero
  mat = np.zeros((size,size))
  mat[r][r] = N
  p = len(mat)
  while mat.max() >= 4:
    for i in range(0,p):
      for j in range(0,p):
        if mat[i][j] >=4:
          if i < p-1:
            mat[i+1][j] += 1
          if i > 0:
            mat[i-1][j] += 1
          if j < p-1:
            mat[i][j+1] += 1
          if j > 0:
            mat[i][j-1] += 1
          mat[i][j] -= 4
        counter += 1
  print("Cantidad de iteraciones:",counter)
  return mat

"""Explique aquí cómo calculó el tamaño que necesita tener el tablero.

Como el arreglo tiene una forma final parecida a la de un círculo, se puede decir que la cantidad de casillas en un circulo está dada por la fórmula: $\pi r^2$. Con esto, definí un r, correspondiente al radio del círculo, y aumenté el tamaño del tablero de una manera conveniente, el doble, para que de esta manera no quede tan ajustado, al cual le asigné el nombre "size". Luego definí la matriz de ceros con coordenadas ("i,j") = ("size","size").
Por otro lado, igual agregué un "caso base" para N<4, de tal manera que se tiene solamente una celda pintada al centro, ya que no se reparte ningún grano de arena. Por esta razón definí la matriz (mat[1][1]).

Ahora ejecute la función para $N=128$:
"""

print(arena(128))

"""A continuación ejecute la función para el valor más grande de $N$ que consiga alcanzar en un tiempo razonable:"""

arena(11000) # reemplace N por el valor máximo que alcanzó a procesar
#se demora aprox 1 min 17 sg

"""## Parte 2
Observe que cuando en una celda hay un número grande de granos de arena, es muy ineficiente ir quitándole de 4 en 4, y sería mejor quitar de una sola vez lo más que se pueda. Podemos mejorar nuestro programa si cambiamos la regla de distribución, y decimos que si en una celda hay un número de granos de arena mayor o igual a 4, le quitamos de una sola vez el mayor múltiplo de 4 posible, y todos esos granos lo repartimos equitativamente entre los vecinos de los cuatro puntos cardinales. Escriba una versión modificada de su función de acuerdo a esta nueva regla.


"""

import matplotlib.pyplot as plt
import numpy as np
import math
def arena2(N):
  if N < 4:
    mat = np.zeros((3,3))
    mat[1][1] = N
    counter = 0
    print(counter)
    return mat
  counter = 0
  r = int(math.sqrt(N/math.pi))
  size = int(r*2) #aumentar el tamaño del tablero
  mat = np.zeros((size,size))
  mat[r][r] = N
  p = len(mat)
  while mat.max() >= 4:
    for i in range(0,p):
      for j in range(0,p):
        if mat[i][j] >=4: #si la celda en cuestion es mayor a 4
          numgranos = (mat[i][j]//4) #cantidad de granos que deberian quedar al centro
          mat[i][j] -= numgranos * 4 #cantidad de granos que deben ser distribuidos a los vecinos
          if i < p-1:
            mat[i+1][j] += numgranos #se agrega a numgrains cantidad de granos que quedan en la celda vecina inmediatamente, no de 1 en 1 como antes.
          if i > 0:
            mat[i-1][j] += numgranos
          if j < p-1:
            mat[i][j+1] += numgranos
          if j > 0:
            mat[i][j-1] += numgranos
        counter += 1
  print("Cantidad de iteraciones:",counter)
  return mat

"""Ahora ejecute la función para $N=128$:"""

arena2(128)

"""A continuación ejecute la función para el valor más grande de  𝑁  que consiga alcanzar en un tiempo razonable. Note que éste número no necesariamente es el mismo que para la función anterior:"""

arena2(24000) # reemplace N por el valor máximo que alcanzó a procesar
#Se demora aprox 1 min 9 sg

"""## Parte 3
Compare a través de una tabla y un gráfico el número de aplicaciones de la regla que hace el programa en la Parte 1 y el de la Parte 2, para los distintos valores de $N$ que usted haya calculado.

Discuta si valió la pena la optimización y discuta también (pero no implemente) otras posibles optimizaciones que se le ocurran.
"""

#tabla con la cantidad de valores
import pandas as pd

df = pd.DataFrame()
#crear una lista del numero 0 al 130 para comparar datos
N = [30,128,500,1500,5000,10000]
arena_1 = [360,8496,156216,1621116,21890232,96526080]
arena_2 = [144,2304,25344,250488,3133260,12230400]

df['N'] = N
df['arena1'] = arena_1
df['arena2'] = arena_2

df.style

#Visualización gráfica del número de aplicaciones de la regla que hace el programa en la parte 1 y en la parte 2 para los distintos valores de N
import matplotlib.pyplot as plt
plt.figure(figsize=(8,6))
N = [30,128,500,1500,5000,10000]
arena_1 = [360,8496,156216,1621116,21890232,96526080]
arena_2 = [144,2304,25344,250488,3133260,12230400]
plt.plot(N,arena_1,label='arena 1')
plt.plot(N,arena_2,label='arena 2')
plt.xlabel('Cantidad N de granos de arena')
plt.ylabel('Cantidad de iteraciones')
plt.title('Ciclos de reparticion de arena')
plt.legend()
plt.show()

"""Como se puede apreciar en el gráfico y en la tabla, la optimización hecha en arena 2 en comparación con arena 1 es necesaria, ya que además de disminuir la cantidad de iteraciones del proceso, se reduce el tiempo en que termina de estabilizarse el código.
Por otro lado, una posible optimización es disminuir el área del tablero, ya sea multiplicándolo por un número menor a 2, o también se puede ocupar una división entera "//" al escribir una expresión para "r", de esta manera se obtiene un índice más exacto para la matriz de ceros.

# Visualización

Para la visualización se recomienda usar arreglos de Numpy y la librería Matplotlib. A continuación un código de ejemplo:
"""

import matplotlib.pyplot as plt
import numpy as np
#Para arena ejemplo con N=10000
mat = arena(10000)
plt.matshow(mat)
plt.show()
#Para arena 2 ejemplo con N=10000
mat = arena2(10000)
plt.matshow(mat)
plt.show()

"""## ¿Qué hay que entregar?

Usted debe crear una copia de este documento (del menú seleccionar "Archivo" o "File" y de ahi la opción "guardar copia en Drive" o "save a copy in Drive"). Este nuevo documento (notebook de Colab) es el que debe modificar para luego compartirlo con la opción "Cualquier usuario de internet con este enlace puede ver esto" (o “Anyone on the internet with this link can view”). Esta opción se encuentra disponible en la parte superior derecha de su notebook, en el botón "Compartir" (o "Share"). Una vez que tenga disponible el enlace, colocarlo en la descripción de la entrega de su tarea. No olvide colocar su nombre dentro del notebook.
"""